package com.ecomm.ws.utils;

public interface ErrorMessage {

	// invalid order errors 
	String INVALID_ORDER = "INVALID ORDER: ";
	String INVALID_ORDER_ID = INVALID_ORDER + "ORDER ID MUST BE NULL";
	String INVALID_ORDER_DATE = INVALID_ORDER + "ORDER DATE MUST BE NULL";
	String INVALID_ORDER_STATUS = INVALID_ORDER + "ORDER STATUS MUST BE NULL";
	String INVALID_ORDER_COST = INVALID_ORDER + "COST OF ORDER MUST BE NULL";

	String INVALID_USER_ID = INVALID_ORDER + "USER ID MUST NOT BE NULL";
	String INVALID_ADDRESS = INVALID_ORDER + "ORDER ADDRESS MUST NOT BE NULL";
	String INVALID_ORDER_DETAILS = INVALID_ORDER
			+ "ORDER DETAILS MUST BE PROVIDED IN KEY-VALUE PAIR";

	// invalid payment - validation errors
	String INVALID_PAYMENT = "INVALID PAYMENT: ";
	String INVALID_STATUS_FOR_PAYMENT = "ORDER IS CLOSED";
	String INVALID_PAYMENT_AMOUNT = "PAYMENT AMOUNT MUST BE SAME WITH THE COST OF THE ORDER";
}
